### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by riefquer** [Mjrovai/OpenCV-Object-Face-Tracking#8]
Dear All,

i have try to running code by command promp and below error has been occured.

==================
(cv) pi@raspberrypi:~/Documents/LatOpenCV $ python object_detection_position.py
[INFO] waiting for camera to warmup...

 Positioning servos to initial position ==> Press 'q' to quit Program 

Traceback (most recent call last):
  File "object_detection_position.py", line 111, in <module>
    if len(cnts) > 0:

  File "objectDetectCoord.py", line 69, in <module>
    if len(cnts) > 0:
TypeError: object of type 'NoneType' has no len()
=====================================
But while running py file by Mu python editor, no error was found.

looking forward any advices, thank you

Arief (Beginner raspberry hobbyist)

**Comment by DarthDemon** [comment]
I have the same problem. I'm going to try and figure out why this error occurs. I will keep you updated.

**Comment by davgonzalvo** [comment]
I have the same problem, any advice?

**Comment by SaadAhmed1122** [comment]
i have also same error accurs please guide us how to resolve it.
